<a href="https://colab.research.google.com/github/abhithale/PANDAS/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv(
    '/content/BigBasket Products.csv',
    engine='python',
    encoding='latin1',
    on_bad_lines='skip'
)# copy the file path and pest it

In [ ]:
df.head(5)

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...

In [ ]:
df.tail(1)

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
27554,27555,United Dreams Go Far Deodorant,Beauty & Hygiene,Men's Grooming,United Colors Of Benetton,214.53,390.0,Men's Deodorants,4.5,The new mens fragrance from the United Dreams ...

In [ ]:
df.head(-1)

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...
...,...,...,...,...,...,...,...,...,...,...
27549,27550,Papad - Garlic Disco,Snacks & Branded Foods,Ready To Cook & Eat,Atish,61.0,61.0,"Papads, Ready To Fry",4.0,Papads are prepared from urad dal flour and sp...
27550,27551,"Wottagirl! Perfume Spray - Heaven, Classic",Beauty & Hygiene,Fragrances & Deos,Layerr,199.2,249.0,Perfume,3.9,Layerr brings you Wottagirl Classic fragrant b...
27551,27552,Rosemary,Gourmet & World Food,Cooking & Baking Needs,Puramate,67.5,75.0,"Herbs, Seasonings & Rubs",4.0,Puramate rosemary is enough to transform a dis...
27552,27553,Peri-Peri Sweet Potato Chips,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",FabBox,200.0,200.0,Nachos & Chips,3.8,We have taken the richness of Sweet Potatoes (...
27553,27554,Green Tea - Pure Original,Beverages,Tea,Tetley,396.0,495.0,Tea Bags,4.2,"Tetley Green Tea with its refreshing pure, ori..."

In [ ]:
df.shape

(27555, 10)

In [ ]:
num_rows = df.shape[0]
num_rows

27555

In [ ]:
df.info() # summery of file like colums , rows , datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27555 entries, 0 to 27554
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   index         27555 non-null  int64
 1   product       27554 non-null  object
 2   category      27555 non-null  object
 3   sub_category  27555 non-null  object
 4   brand         27554 non-null  object
 5   sale_price    27555 non-null  float64
 6   market_price  27555 non-null  float64
 7   type          27555 non-null  object
 8   rating        18929 non-null  float64
 9   description   27440 non-null  object
dtypes: float64(3), int64(1), object(6)
memory usage: 2.1+ MB

In [ ]:

df.describe() # returns only int and float values that are stoer in file

             index    sale_price  market_price        rating
count  27555.00000  27555.000000  27555.000000  18929.000000
mean   13778.00000    322.514808    382.056664      3.943410
std     7954.58767    486.263116    581.730717      0.739063
min        1.00000      2.450000      3.000000      1.000000
25%     6889.50000     95.000000    100.000000      3.700000
50%    13778.00000    190.000000    220.000000      4.100000
75%    20666.50000    359.000000    425.000000      4.300000
max    27555.00000  12500.000000  12500.000000      5.000000

In [ ]:

df[['index' , 'sale_price']].describe() # to load colums that we want to work on

             index    sale_price
count  27555.00000  27555.000000
mean   13778.00000    322.514808
std     7954.58767    486.263116
min        1.00000      2.450000
25%     6889.50000     95.000000
50%    13778.00000    190.000000
75%    20666.50000    359.000000
max    27555.00000  12500.000000

In [ ]:
df[['rating']].describe()

             rating
count  18929.000000
mean       3.943410
std        0.739063
min        1.000000
25%        3.700000
50%        4.100000
75%        4.300000
max        5.000000

In [ ]:

df.columns

Index(['index', 'product', 'category', 'sub_category', 'brand', 'sale_price',
       'market_price', 'type', 'rating', 'description'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=27555, step=1)

In [ ]:
df.columns.tolist() # print columns name in form of list

['index',
 'product',
 'category',
 'sub_category',
 'brand',
 'sale_price',
 'market_price',
 'type',
 'rating',
 'description']

In [ ]:
len(df.index)

27555

In [ ]:

df.index

RangeIndex(start=0, stop=27555, step=1)

#.dtypes in pandas
- comman Data Type in pandas:
- object - Text/string data
- int64 - integer number
- float64 - Decimal number
- datetime64 - Dates and time

In [ ]:
df.dtypes

index             int64
product          object
category         object
sub_category     object
brand            object
sale_price      float64
market_price    float64
type             object
rating          float64
description      object
dtype: object

In [ ]:
df.dtypes.value_counts() # retunrs in which column which type of data have stored

object     6
float64    3
int64      1
Name: count, dtype: int64

In [ ]:
df['product']

0                   Garlic Oil - Vegetarian Capsule 500 mg
1                                    Water Bottle - Orange
2                           Brass Angle Deep - Plain, No.2
3        Cereal Flip Lid Container/Storage Jar - Assort...
4                       Creme Soft Soap - For Hands & Body
                               ...
27550           Wottagirl! Perfume Spray - Heaven, Classic
27551                                             Rosemary
27552                         Peri-Peri Sweet Potato Chips
27553                            Green Tea - Pure Original
27554                       United Dreams Go Far Deodorant
Name: product, Length: 27555, dtype: object

In [ ]:
df_1 = df[['product','rating','index']]
df_1

                                                 product  rating  index
0                 Garlic Oil - Vegetarian Capsule 500 mg     4.1      1
1                                  Water Bottle - Orange     2.3      2
2                         Brass Angle Deep - Plain, No.2     3.4      3
3      Cereal Flip Lid Container/Storage Jar - Assort...     3.7      4
4                     Creme Soft Soap - For Hands & Body     4.4      5
...                                                  ...     ...    ...
27550         Wottagirl! Perfume Spray - Heaven, Classic     3.9  27551
27551                                           Rosemary     4.0  27552
27552                       Peri-Peri Sweet Potato Chips     3.8  27553
27553                          Green Tea - Pure Original     4.2  27554
27554                     United Dreams Go Far Deodorant     4.5  27555

[27555 rows x 3 columns]

In [ ]:
df.select_dtypes(include=['int64', 'float64']).columns

Index(['index', 'sale_price', 'market_price', 'rating'], dtype='object')

#practice

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/BigBasket Products.csv')

In [ ]:
df.shape

(27555, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27555 entries, 0 to 27554
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   index         27555 non-null  int64
 1   product       27554 non-null  object
 2   category      27555 non-null  object
 3   sub_category  27555 non-null  object
 4   brand         27554 non-null  object
 5   sale_price    27555 non-null  float64
 6   market_price  27555 non-null  float64
 7   type          27555 non-null  object
 8   rating        18929 non-null  float64
 9   description   27440 non-null  object
dtypes: float64(3), int64(1), object(6)
memory usage: 2.1+ MB

In [ ]:
df.head()

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...

In [ ]:
df.tail()

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
27550,27551,"Wottagirl! Perfume Spray - Heaven, Classic",Beauty & Hygiene,Fragrances & Deos,Layerr,199.20,249.0,Perfume,3.9,Layerr brings you Wottagirl Classic fragrant b...
27551,27552,Rosemary,Gourmet & World Food,Cooking & Baking Needs,Puramate,67.50,75.0,"Herbs, Seasonings & Rubs",4.0,Puramate rosemary is enough to transform a dis...
27552,27553,Peri-Peri Sweet Potato Chips,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",FabBox,200.00,200.0,Nachos & Chips,3.8,We have taken the richness of Sweet Potatoes (...
27553,27554,Green Tea - Pure Original,Beverages,Tea,Tetley,396.00,495.0,Tea Bags,4.2,"Tetley Green Tea with its refreshing pure, ori..."
27554,27555,United Dreams Go Far Deodorant,Beauty & Hygiene,Men's Grooming,United Colors Of Benetton,214.53,390.0,Men's Deodorants,4.5,The new mens fragrance from the United Dreams ...

In [ ]:
df.columns

Index(['index', 'product', 'category', 'sub_category', 'brand', 'sale_price',
       'market_price', 'type', 'rating', 'description'],
      dtype='object')

In [ ]:
df.sort_values('sale_price' , ascending = True)

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
26976,26977,Curry Leaves,Fruits & Vegetables,Herbs & Seasonings,Fresho,2.45,15.00,Indian & Exotic Herbs,NaN,"With dark green and glossy appearance, curry l..."
21312,21313,Serum,Beauty & Hygiene,Hair Care,Livon,3.00,3.00,Hair Oil & Serum,2.5,"Instantly Softens and Smoothens Dry, Rough, Ta..."
14184,14185,"Tomato - Local, Organically Grown",Fruits & Vegetables,Organic Fruits & Vegetables,Fresho,5.00,6.25,Organic Vegetables,NaN,Fresho brings to you an exquisite range of loc...
27490,27491,50-50 Timepass Salted Biscuits,Snacks & Branded Foods,Biscuits & Cookies,Britannia,5.00,5.00,Salted Biscuits,4.2,Britannia 50-50 Timepass Salted Biscuits are a...
22178,22179,Tiger Elaichi Cream Biscuits,Snacks & Branded Foods,Biscuits & Cookies,Britannia,5.00,5.00,Glucose & Milk Biscuits,4.2,Britannia Tiger Elaichi Cream Biscuits are a t...
...,...,...,...,...,...,...,...,...,...,...
2781,2782,Extra Virgin Olive Oil,Gourmet & World Food,Oils & Vinegar,Abbies,7299.00,7299.00,Extra Virgin Olive Oil,NaN,Suitable to cook Indian meals due to its neutr...
23082,23083,"Gas Stove-4 Burner Royale Plus Schott Glass, B...","Kitchen, Garden & Pets",Cookware & Non Stick,Prestige,7999.00,12245.00,Gas Stove,NaN,Prestige Royale Plus Gas Stove. Add a Touch of...
12669,12670,Epilator SE9-9961 Legs-Body-Face,Beauty & Hygiene,Feminine Hygiene,Braun,8184.44,10769.00,Hair Removal,NaN,This cordless epilator has a sonic exfoliation...
21761,21762,Pet Food - N&D Team Breeder Puppy Top Farmina,"Kitchen, Garden & Pets",Pet Food & Accessories,Farmina,10090.00,10090.00,Pet Meals & Treats,NaN,Dog Food Adult Health Nutritional Dog Food.
25301,25302,Bravura Clipper,"Kitchen, Garden & Pets",Pet Food & Accessories,Wahl,12500.00,12500.00,Pet Cleaning & Grooming,NaN,The bravura clipper is a must-have clipper for...

In [ ]:
df.rename(columns={'sale_price' : 'sale_price1'})

,index,product,category,sub_category,brand,sale_price1,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.00,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.00,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.00,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.00,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.00,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...
...,...,...,...,...,...,...,...,...,...,...
27550,27551,"Wottagirl! Perfume Spray - Heaven, Classic",Beauty & Hygiene,Fragrances & Deos,Layerr,199.20,249.0,Perfume,3.9,Layerr brings you Wottagirl Classic fragrant b...
27551,27552,Rosemary,Gourmet & World Food,Cooking & Baking Needs,Puramate,67.50,75.0,"Herbs, Seasonings & Rubs",4.0,Puramate rosemary is enough to transform a dis...
27552,27553,Peri-Peri Sweet Potato Chips,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",FabBox,200.00,200.0,Nachos & Chips,3.8,We have taken the richness of Sweet Potatoes (...
27553,27554,Green Tea - Pure Original,Beverages,Tea,Tetley,396.00,495.0,Tea Bags,4.2,"Tetley Green Tea with its refreshing pure, ori..."
27554,27555,United Dreams Go Far Deodorant,Beauty & Hygiene,Men's Grooming,United Colors Of Benetton,214.53,390.0,Men's Deodorants,4.5,The new mens fragrance from the United Dreams ...

In [ ]:
df.isnull().sum()

index              0
product            1
category           0
sub_category       0
brand              1
sale_price         0
market_price       0
type               0
rating          8626
description      115
dtype: int64

In [ ]:
df['rating'].isnull().sum()

np.int64(8626)

In [ ]:
df['product'].isnull().sum()

np.int64(1)

In [ ]:
df.dropna() # if one value are missing then all row will be deleted

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.00,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.00,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.00,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.00,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.00,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...
...,...,...,...,...,...,...,...,...,...,...
27550,27551,"Wottagirl! Perfume Spray - Heaven, Classic",Beauty & Hygiene,Fragrances & Deos,Layerr,199.20,249.0,Perfume,3.9,Layerr brings you Wottagirl Classic fragrant b...
27551,27552,Rosemary,Gourmet & World Food,Cooking & Baking Needs,Puramate,67.50,75.0,"Herbs, Seasonings & Rubs",4.0,Puramate rosemary is enough to transform a dis...
27552,27553,Peri-Peri Sweet Potato Chips,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",FabBox,200.00,200.0,Nachos & Chips,3.8,We have taken the richness of Sweet Potatoes (...
27553,27554,Green Tea - Pure Original,Beverages,Tea,Tetley,396.00,495.0,Tea Bags,4.2,"Tetley Green Tea with its refreshing pure, ori..."
27554,27555,United Dreams Go Far Deodorant,Beauty & Hygiene,Men's Grooming,United Colors Of Benetton,214.53,390.0,Men's Deodorants,4.5,The new mens fragrance from the United Dreams ...

In [ ]:
df.dropna(how='all') # here if the row is all empty then it will delete the all row otherwise it will keep at is
# how = 'all' - it select only that roa who have all null values

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.00,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.00,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.00,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.00,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.00,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...
...,...,...,...,...,...,...,...,...,...,...
27550,27551,"Wottagirl! Perfume Spray - Heaven, Classic",Beauty & Hygiene,Fragrances & Deos,Layerr,199.20,249.0,Perfume,3.9,Layerr brings you Wottagirl Classic fragrant b...
27551,27552,Rosemary,Gourmet & World Food,Cooking & Baking Needs,Puramate,67.50,75.0,"Herbs, Seasonings & Rubs",4.0,Puramate rosemary is enough to transform a dis...
27552,27553,Peri-Peri Sweet Potato Chips,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",FabBox,200.00,200.0,Nachos & Chips,3.8,We have taken the richness of Sweet Potatoes (...
27553,27554,Green Tea - Pure Original,Beverages,Tea,Tetley,396.00,495.0,Tea Bags,4.2,"Tetley Green Tea with its refreshing pure, ori..."
27554,27555,United Dreams Go Far Deodorant,Beauty & Hygiene,Men's Grooming,United Colors Of Benetton,214.53,390.0,Men's Deodorants,4.5,The new mens fragrance from the United Dreams ...

In [ ]:
df.dropna(axis = 1)

,index,category,sub_category,sale_price,market_price,type
0,1,Beauty & Hygiene,Hair Care,220.00,220.0,Hair Oil & Serum
1,2,"Kitchen, Garden & Pets",Storage & Accessories,180.00,180.0,Water & Fridge Bottles
2,3,Cleaning & Household,Pooja Needs,119.00,250.0,Lamp & Lamp Oil
3,4,Cleaning & Household,Bins & Bathroom Ware,149.00,176.0,"Laundry, Storage Baskets"
4,5,Beauty & Hygiene,Bath & Hand Wash,162.00,162.0,Bathing Bars & Soaps
...,...,...,...,...,...,...
27550,27551,Beauty & Hygiene,Fragrances & Deos,199.20,249.0,Perfume
27551,27552,Gourmet & World Food,Cooking & Baking Needs,67.50,75.0,"Herbs, Seasonings & Rubs"
27552,27553,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",200.00,200.0,Nachos & Chips
27553,27554,Beverages,Tea,396.00,495.0,Tea Bags
27554,27555,Beauty & Hygiene,Men's Grooming,214.53,390.0,Men's Deodorants

In [ ]:
df.fillna(method = 'ffill') # null ko null ke pehele ke index ki value assigne krta hai

/tmp/ipython-input-155/3504009942.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill') # null ko null ke pehele ke index ki value assigne krta hai

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.00,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.00,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.00,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.00,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.00,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...
...,...,...,...,...,...,...,...,...,...,...
27550,27551,"Wottagirl! Perfume Spray - Heaven, Classic",Beauty & Hygiene,Fragrances & Deos,Layerr,199.20,249.0,Perfume,3.9,Layerr brings you Wottagirl Classic fragrant b...
27551,27552,Rosemary,Gourmet & World Food,Cooking & Baking Needs,Puramate,67.50,75.0,"Herbs, Seasonings & Rubs",4.0,Puramate rosemary is enough to transform a dis...
27552,27553,Peri-Peri Sweet Potato Chips,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",FabBox,200.00,200.0,Nachos & Chips,3.8,We have taken the richness of Sweet Potatoes (...
27553,27554,Green Tea - Pure Original,Beverages,Tea,Tetley,396.00,495.0,Tea Bags,4.2,"Tetley Green Tea with its refreshing pure, ori..."
27554,27555,United Dreams Go Far Deodorant,Beauty & Hygiene,Men's Grooming,United Colors Of Benetton,214.53,390.0,Men's Deodorants,4.5,The new mens fragrance from the United Dreams ...

In [ ]:
df.fillna(method = 'bfill') # null ke niche ki value ko null ko bhi assign kr dega

/tmp/ipython-input-155/462884640.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'bfill') # null ke niche ki value ko null ko bhi assign kr dega

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.00,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.00,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.00,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.00,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.00,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...
...,...,...,...,...,...,...,...,...,...,...
27550,27551,"Wottagirl! Perfume Spray - Heaven, Classic",Beauty & Hygiene,Fragrances & Deos,Layerr,199.20,249.0,Perfume,3.9,Layerr brings you Wottagirl Classic fragrant b...
27551,27552,Rosemary,Gourmet & World Food,Cooking & Baking Needs,Puramate,67.50,75.0,"Herbs, Seasonings & Rubs",4.0,Puramate rosemary is enough to transform a dis...
27552,27553,Peri-Peri Sweet Potato Chips,Gourmet & World Food,"Snacks, Dry Fruits, Nuts",FabBox,200.00,200.0,Nachos & Chips,3.8,We have taken the richness of Sweet Potatoes (...
27553,27554,Green Tea - Pure Original,Beverages,Tea,Tetley,396.00,495.0,Tea Bags,4.2,"Tetley Green Tea with its refreshing pure, ori..."
27554,27555,United Dreams Go Far Deodorant,Beauty & Hygiene,Men's Grooming,United Colors Of Benetton,214.53,390.0,Men's Deodorants,4.5,The new mens fragrance from the United Dreams ...

In [ ]:
df[df['brand'] == 'Nivea']

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.00,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...
318,319,Milk Delights Face Wash With Honey For Dry Skin,Beauty & Hygiene,Skin Care,Nivea,86.40,90.0,Face Care,4.2,Presenting New Nivea Milk Delights Face Wash w...
412,413,Original Care Lip Balm For 24h Moisture With S...,Beauty & Hygiene,Skin Care,Nivea,114.80,140.0,Lip Care,4.3,Nivea Original Care Lip Blam nourishes lips in...
2538,2539,Extra Whitening Cell Repair Body Lotion - SPF ...,Beauty & Hygiene,Skin Care,Nivea,249.60,260.0,Body Care,3.6,The ultra-light formula of Nivea Express Hydra...
2582,2583,Whitening Smooth Skin Women Deodorant Roll On ...,Beauty & Hygiene,Fragrances & Deos,Nivea,139.30,199.0,Women's Deodorants,4.4,Care for your underarms with NIVEA Whitening S...
...,...,...,...,...,...,...,...,...,...,...
26911,26912,Body Wash - Frangipani & Oil Shower Gel,Beauty & Hygiene,Bath & Hand Wash,Nivea,339.15,399.0,Shower Gel & Body Wash,4.0,Give your skin refreshing care with Nivea fran...
26992,26993,Milk Delights Face Wash With Besan For Oily Skin,Beauty & Hygiene,Skin Care,Nivea,86.40,90.0,Face Care,4.1,Presenting New Nivea Milk Delights Face Wash h...
27080,27081,"Women Deodorant Roll On - Protect & Care, Non-...",Beauty & Hygiene,Men's Grooming,Nivea,181.30,185.0,Men's Deodorants,4.4,Nivea Protect & Care is the only roll on with ...
27153,27154,Cherry Shine Lip Balm - 24h Moisture With Natu...,Beauty & Hygiene,Makeup,Nivea,139.00,185.0,Lips,4.3,Nivea charming Cherry Shine lip care delights ...
27167,27168,Milk Delights Women Face Wash With Turmeric Fo...,Beauty & Hygiene,Skin Care,Nivea,131.25,175.0,Face Care,4.5,Presenting New NIVEA Milk Delights Face Wash. ...

**loc[]*** **iloc[]**

In [ ]:
import pandas as pd
import numpy as np


data = {
    'roll no ' : [101,102,103],
    'name' : ["Abhishek","janhavi","sakshi"],
    'marks' : [90,45,80]

}


df = pd.DataFrame(data , index = ['x','y','z'])

In [ ]:
df

   roll no       name  marks
x       101  Abhishek     90
y       102   janhavi     45
z       103    sakshi     80

In [ ]:
df.loc['x'] # we assigen index name and accesing it with help of loc[]

roll no          101
name        Abhishek
marks             90
Name: x, dtype: object

In [ ]:
df.iloc[1] # use to acces with inbuilt indexing

roll no         102
name        janhavi
marks            45
Name: y, dtype: object